options {
  directory "/var/named";

  listen-on port 53 { 127.0.0.1; };
  listen-on-v6 { none; };

  allow-query { localhost; 127.0.0.1; };
  recursion yes;
  allow-recursion { localhost; 127.0.0.1; };

  forwarders {
    8.8.8.8;
    1.1.1.1;
  };

  dnssec-validation no;
  auth-nxdomain no;
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
