services:
  zimbra-rocky9:
    build: .
    image: docker-zimbra-10-rocky9-dwinar:latest
    container_name: zimbra-rocky9
    hostname: zimbra10.dwinar.web.id
    privileged: true
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 1.1.1.1
    environment:
      PASSWORD: "ChangeMe123!"
      TIMEZONE: "Asia/Jakarta"
      DNS_FORWARDER_1: "8.8.8.8"
      DNS_FORWARDER_2: "1.1.1.1"
    ports:
      - "25:25"
      - "80:80"
      - "443:443"
      - "465:465"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "7071:7071"
      - "9071:9071"
    volumes:
      - zimbra-data:/opt/zimbra
    restart: unless-stopped

volumes:
  zimbra-data:
